import java.util.HashMap;

/**
 * Class containing sub-location for every country.
 * It can be used when looking for the locations of a particular animal.
 */
public abstract class CountriesLocations {
    private static final HashMap<String, String> countriesLocations = new HashMap<>();

    static {
        countriesLocations.put("afghanistan", "middle east");
        countriesLocations.put("albania", "south europe");
        countriesLocations.put("algeria", "north africa");
        countriesLocations.put("andorra", "west europe");
        countriesLocations.put("angola", "south africa");
        countriesLocations.put("antigua and barbuda", "central america");
        countriesLocations.put("argentina", "south america");
        countriesLocations.put("armenia", "west asia");
        countriesLocations.put("australia", "australia");
        countriesLocations.put("austria", "central europe");
        countriesLocations.put("azerbaijan", "west asia");
        countriesLocations.put("bahamas", "central america");
        countriesLocations.put("bahrain", "middle east");
        countriesLocations.put("bangladesh", "east asia");
        countriesLocations.put("barbados", "central america");
        countriesLocations.put("belarus", "east europe");
        countriesLocations.put("belgium", "west europe");
        countriesLocations.put("belize", "central america");
        countriesLocations.put("benin", "west africa");
        countriesLocations.put("bhutan", "east asia");
        countriesLocations.put("bolivia", "south america");
        countriesLocations.put("bosnia and herzegovina", "south europe");
        countriesLocations.put("botswana", "south africa");
        countriesLocations.put("brazil", "south america");
        countriesLocations.put("brunei", "east asia");
        countriesLocations.put("bulgaria", "south europe");
        countriesLocations.put("burkina faso", "west africa");
        countriesLocations.put("burundi", "central africa");
        countriesLocations.put("côte d'ivoire", "west africa");
        countriesLocations.put("ivory coast", "west africa");
        countriesLocations.put("cabo verde", "west africa");
        countriesLocations.put("cambodia", "east asia");
        countriesLocations.put("cameroon", "central africa");
        countriesLocations.put("canada", "north america");
        countriesLocations.put("central african republic", "central africa");
        countriesLocations.put("chad", "central africa");
        countriesLocations.put("chile", "south america");
        countriesLocations.put("china", "china");
        countriesLocations.put("colombia", "south america");
        countriesLocations.put("comoros", "south africa");
        countriesLocations.put("congo", "central africa");
        countriesLocations.put("costa rica", "central america");
        countriesLocations.put("croatia", "south europe");
        countriesLocations.put("cuba", "central america");
        countriesLocations.put("cyprus", "south europe");
        countriesLocations.put("czechia", "central europe");
        countriesLocations.put("czech republic", "central europe");
        countriesLocations.put("democratic republic of the congo", "central africa");
        countriesLocations.put("denmark", "north europe");
        countriesLocations.put("djibouti", "east africa");
        countriesLocations.put("dominica", "central america");
        countriesLocations.put("dominican republic", "central america");
        countriesLocations.put("ecuador", "south america");
        countriesLocations.put("egypt", "north africa");
        countriesLocations.put("el salvador", "central america");
        countriesLocations.put("equatorial guinea", "central africa");
        countriesLocations.put("eritrea", "east africa");
        countriesLocations.put("estonia", "north europe");
        countriesLocations.put("eswatini", "north europe");
        countriesLocations.put("ethiopia", "east africa");
        countriesLocations.put("fiji", "pacific");
        countriesLocations.put("finland", "north europe");
        countriesLocations.put("france", "west europe");
        countriesLocations.put("gabon", "central africa");
        countriesLocations.put("gambia", "west africa");
        countriesLocations.put("georgia", "west asia");
        countriesLocations.put("germany", "west europe");
        countriesLocations.put("ghana", "west africa");
        countriesLocations.put("greece", "south europe");
        countriesLocations.put("grenada", "central america");
        countriesLocations.put("guatemala", "central america");
        countriesLocations.put("guinea", "west africa");
        countriesLocations.put("guinea-bissau", "west africa");
        countriesLocations.put("guyana", "south america");
        countriesLocations.put("haiti", "central america");
        countriesLocations.put("honduras", "central america");
        countriesLocations.put("hungary", "central europe");
        countriesLocations.put("iceland", "iceland");
        countriesLocations.put("india", "south asia");
        countriesLocations.put("indonesia", "south asia");
        countriesLocations.put("iran", "middle east");
        countriesLocations.put("iraq", "middle east");
        countriesLocations.put("ireland", "west europe");
        countriesLocations.put("israel", "middle east");
        countriesLocations.put("italy", "south europe");
        countriesLocations.put("jamaica", "central america");
        countriesLocations.put("japan", "japan");
        countriesLocations.put("jordan", "middle east");
        countriesLocations.put("kazakhstan", "central asia");
        countriesLocations.put("kenya", "east africa");
        countriesLocations.put("kiribati", "pacific");
        countriesLocations.put("kuwait", "middle east");
        countriesLocations.put("kyrgyzstan", "central asia");
        countriesLocations.put("laos", "east asia");
        countriesLocations.put("latvia", "north europe");
        countriesLocations.put("lebanon", "middle east");
        countriesLocations.put("lesotho", "south africa");
        countriesLocations.put("liberia", "west africa");
        countriesLocations.put("libya", "north africa");
        countriesLocations.put("liechtenstein", "central europe");
        countriesLocations.put("lithuania", "north europe");
        countriesLocations.put("luxembourg", "west europe");
        countriesLocations.put("madagascar", "madagascar");
        countriesLocations.put("malawi", "central africa");
        countriesLocations.put("malaysia", "east asia");
        countriesLocations.put("maldives", "south asia");
        countriesLocations.put("mali", "west africa");
        countriesLocations.put("malta", "south africa");
        countriesLocations.put("marshall islands", "pacific");
        countriesLocations.put("mauritania", "west africa");
        countriesLocations.put("mauritius", "south africa");
        countriesLocations.put("mexico", "central america");
        countriesLocations.put("micronesia", "pacific");
        countriesLocations.put("moldova", "east europe");
        countriesLocations.put("monaco", "west europe");
        countriesLocations.put("mongolia", "central asia");
        countriesLocations.put("montenegro", "south europe");
        countriesLocations.put("morocco", "north africa");
        countriesLocations.put("mozambique", "south africa");
        countriesLocations.put("myanmar", "east asia");
        countriesLocations.put("namibia", "south africa");
        countriesLocations.put("nauru", "pacific");
        countriesLocations.put("nepal", "east asia");
        countriesLocations.put("netherlands", "west europe");
        countriesLocations.put("new zealand", "new zealand");
        countriesLocations.put("nicaragua", "central america");
        countriesLocations.put("niger", "west africa");
        countriesLocations.put("nigeria", "west africa");
        countriesLocations.put("north korea", "east asia");
        countriesLocations.put("north macedonia", "south europe");
        countriesLocations.put("norway", "north europe");
        countriesLocations.put("oman", "middle east");
        countriesLocations.put("pakistan", "middle east");
        countriesLocations.put("palau", "pacific");
        countriesLocations.put("palestine", "middle east");
        countriesLocations.put("panama", "central america");
        countriesLocations.put("papua new guinea", "new guinea");
        countriesLocations.put("paraguay", "south america");
        countriesLocations.put("peru", "south america");
        countriesLocations.put("philippines", "east asia");
        countriesLocations.put("poland", "central europe");
        countriesLocations.put("portugal", "west europe");
        countriesLocations.put("qatar", "middle east");
        countriesLocations.put("romania", "south europe");
        countriesLocations.put("russia", "eurasia");
        countriesLocations.put("rwanda", "central africa");
        countriesLocations.put("saint kitts and nevis", "central america");
        countriesLocations.put("saint lucia", "central america");
        countriesLocations.put("saint vincent and the grenadines", "central america");
        countriesLocations.put("samoa", "pacific");
        countriesLocations.put("sao tome and principe", "west africa");
        countriesLocations.put("saudi arabia", "middle east");
        countriesLocations.put("senegal", "west africa");
        countriesLocations.put("serbia", "south europe");
        countriesLocations.put("seychelles", "south africa");
        countriesLocations.put("sierra leone", "west africa");
        countriesLocations.put("singapore", "east asia");
        countriesLocations.put("slovakia", "central europe");
        countriesLocations.put("slovenia", "south europe");
        countriesLocations.put("solomon islands", "pacific");
        countriesLocations.put("somalia", "east africa");
        countriesLocations.put("south africa", "south africa");
        countriesLocations.put("south korea", "east asia");
        countriesLocations.put("south sudan", "east africa");
        countriesLocations.put("spain", "west europe");
        countriesLocations.put("sri lanka", "south asia");
        countriesLocations.put("sudan", "east africa");
        countriesLocations.put("suriname", "south america");
        countriesLocations.put("sweden", "north europe");
        countriesLocations.put("switzerland", "central europe");
        countriesLocations.put("syria", "middle east");
        countriesLocations.put("tajikistan", "central asia");
        countriesLocations.put("tanzania", "east africa");
        countriesLocations.put("thailand", "east asia");
        countriesLocations.put("timor-leste", "east asia");
        countriesLocations.put("east timor", "east asia");
        countriesLocations.put("togo", "west africa");
        countriesLocations.put("tonga", "pacific");
        countriesLocations.put("trinidad and tobago", "central america");
        countriesLocations.put("tunisia", "north africa");
        countriesLocations.put("turkey", "west asia");
        countriesLocations.put("turkmenistan", "central asia");
        countriesLocations.put("tuvalu", "pacific");
        countriesLocations.put("uganda", "east africa");
        countriesLocations.put("ukraine", "east europe");
        countriesLocations.put("united arab emirates", "middle east");
        countriesLocations.put("united kingdom", "west europe");
        countriesLocations.put("britain", "west europe");
        countriesLocations.put("united states", "north america");
        countriesLocations.put("uruguay", "south america");
        countriesLocations.put("uzbekistan", "central asia");
        countriesLocations.put("vanuatu", "pacific");
        countriesLocations.put("venezuela", "south america");
        countriesLocations.put("vietnam", "east asia");
        countriesLocations.put("yemen", "middle east");
        countriesLocations.put("zambia", "south africa");
        countriesLocations.put("zimbabwe", "south africa");
    }

    public static HashMap<String, String> getCountriesLocations() {
        return countriesLocations;
    }
}
